apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  application.resourceTrackingMethod: annotation
  admin.enabled: 'true'
  statusbadge.enabled: 'true'
  users.anonymous.enabled: 'false'
  url: 'https://argocd.kubefirst.dev'
  oidc.config: |
    name: Vault
    issuer: https://vault.kubefirst.dev/v1/identity/oidc/provider/kubefirst
    clientID: $argocd-oidc-secret:clientId
    clientSecret: $argocd-oidc-secret:clientSecret
    requestedScopes: ["openid", "groups", "user", "profile", "email"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
  resource.customizations: |
    argoproj.io/Application:
      health.lua: |
        hs = {}
        hs.status = "Progressing"
        hs.message = ""
        if obj.status ~= nil then
          if obj.status.health ~= nil then
            hs.status = obj.status.health.status
            if obj.status.health.message ~= nil then
              hs.message = obj.status.health.message
            end
          end
        end
        return hs
